iptables/iptables-apply usr/sbin
iptables/iptables.xslt usr/share/iptables
usr/lib/*/xtables/libip*.so
usr/lib/*/xtables/libxt_*.so
usr/sbin/ip6tables sbin
usr/sbin/ip6tables-restore sbin
usr/sbin/ip6tables-save sbin
usr/sbin/iptables sbin
usr/sbin/iptables-restore sbin
usr/sbin/iptables-save sbin
usr/sbin/nf* usr/sbin
usr/sbin/xtables-multi sbin
usr/share/man/man1
usr/share/man/man8
howtos/NAT*html debian/tmp/howtos/packet*html usr/share/doc/iptables/html
