#!/bin/bash
#run coredump parse command automatically
#created by chenxi 2022-01-22

GDBPATH=/opt/toolchains/crosstools-arm-gcc-5.5-linux-4.1-glibc-2.26-binutils-2.28.1/usr/bin/arm-buildroot-linux-gnueabi-gdb
PWD=`pwd`

usage()
{
cat << EOF
hgcoredump [your-exe-file-path] [your-core-dump-file] [your-fs.install-path]
For example:

run hgcoredump in your project dir(where ./h command exists):
hgcoredump hgsApps/userspace/coredumptest/coredumptest core-svn-966-coredumptest

or run hgcoredump in other dir(use absolute path):
hgcoredump /home/user/yourProjDir/userspace/coredumptest/coredumptest /home/user/yourProjDir/core-svn-966-coredumptest /home/user/yourProjDir/images/fs.install/
EOF
}



case $# in
	0|1)
		usage
		exit 0
		;;
		
#	1)
#		para1=$1
#		echo ${para1:0:2}
#		;;
		
	2)
		para1=$1
		para2=$2
		para3=~/images/fs.install/
		;;
		
	3)
		para1=$1
		para2=$2
		para3=$3
		;;
	*)
		usage
		exit 0
		;;
esac


cat << EOF  > ~/runCoredumpCmd
set sysroot ${para3}
bt
EOF

#echo ${GDBPATH} ${para1} ${para2} -command=~/runCoredumpCmd

${GDBPATH} ${para1} ${para2} -command=~/runCoredumpCmd
