#!/bin/sh
printf "#---\nuptime:%s, date:%s, " `awk '{print $1}' /proc/uptime` `date +%Y-%m-%d_%H:%M:%S` 
awk '{if($1 ~ /Mem/) printf "%s %s, ", $1, $2}' /proc/meminfo
printf "\n+\n"

grep "^Pid:\|Name:\|VmRSS" /proc/[1-9]*/status | 
awk -F ':' '{print $2 $3}' | 
awk '{if ($1=="Name") printf "\n%-20s", $2;else if ($1=="Pid") printf "%5d ", $2; else printf " %5s %s  ", $2, $3};END {printf "\n"}' | 
awk '{if (NF==4 && $1 !~ /awk/ && $1 !~ /grep/&& $1 !~ /sort/) printf "%5d %-20s %5s %s\n", $2, $1, $3, $4}' |  awk '{print $1,$2,$3}' |
sort -k 1