@startuml
    [*] -r-> 底层
    底层 -u[#blue]-> 应用
    底层 --> linux
    linux --> driver
    driver --> char设备
    driver --> 通信接口
    driver --> network

    底层 --> RTOS
    底层 --> 裸机

    应用 -r[#blue]-> 人机操作
    人机操作 -u-> 输入设备
    应用 --> 数据收集
    数据收集 --> 传感器
    数据收集 --> 文本固定数据
    数据收集 --> python数据处理
    python数据处理 --> 文本固定数据: 生成
    传感器 --> 文本固定数据: 生成

    人机操作 -u-> GUI
    GUI -r-> QT

    QT --> 资源管理
    资源管理 --> 电影管理
    电影管理 --> 类型筛选
    电影管理 --> 自动分类
    自动分类 --> 下载时间
    自动分类 --> 读取时间
    自动分类 --> 类型分类
    自动分类 --> 最佳影片
    最佳影片 --> 分级
    分级 : 1-10级
@enduml